### ISSUE TITLE
Observer added to an assessment - email says added as an assessor. 

### ISSUE THREAD

**Issue by andyjones81** [DFE-Digital/dops-sas#77]
Need to make the email that goes to people added as observers to say they have been added as an obersever. Currently, it says added as assessor as the title but then the body content says observer.

```
You’ve been added as an assessor for a alpha service assessment

Thank you for signing up as an assessor for the <service name>

You’ve been added as the observer to the panel.
```

**Comment by andyjones81** [comment]
@kerryalyons can you create a new template which replicates the admin template: Assessor added to panel and call it "Observer added to panel" and change the content from "assessor" to "observer" - leave the Assessor added to panel template.

**Comment by kerryalyons** [comment]
Is it that observers are getting the assessor email? 
Assessor template: 7a32d759-c26e-4a40-840a-2c072c41ff96

### New observer email in Notify

Template: [1da2c1ac-601a-4488-97c5-5655d0ec77d2 ](https://www.notifications.service.gov.uk/services/eca68f37-efd8-46c8-b5ee-ad812b8eaaae/templates/1da2c1ac-601a-4488-97c5-5655d0ec77d2)

Ready to link to service.

Check: is observerName a parameter in the service?

**Comment by kerryalyons** [comment]
@andyjones81 just check is observerName a parameter in the service? Also, have a read of the content, I've mirrored the assessor one, telling them they will have access to artefacts and ability to see who is on the panel - is this correct for observers?
